name: sol-miner-loop

on:
  workflow_dispatch:

jobs:
  continuous-mining:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Maksimal durasi job: 6 jam

    steps:
      - name: Start Loop Mining (5 Workers)
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)

          echo "Mulai Mining Loop..."

          for i in {1..5}; do
            ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.Worker$i -p x --threads=4 &
            sleep 2
          done

          echo "Semua Worker Jalan. Menunggu sampai timeout (6 jam)..."
          sleep 21600  # 6 jam
